### ISSUE TITLE
Cannot Build CtsHelper

### ISSUE THREAD

**Issue by ghost** [mgwoo/CtsHelper#1]
I'm running on FreeBSD 12.0, and (as far as I know) I have tried compiling with Clang 6.0.1 and gcc 8.3.0. Both times, I got tons of compilation errors. I have attached log files to this post. What gcc version are you using to build?
[clang_make.log](https://github.com/mgwoo/CtsHelper/files/3499853/clang_make.log)
[gcc_make.log](https://github.com/mgwoo/CtsHelper/files/3499854/gcc_make.log)

**Comment by mgwoo** [comment]
I've faced with the same problem before in Mac with clang compiler (OS X), when the namespace and class name is exactly the same.

I'll somehow change my code to support this, but I've found weird bugs on Mac's clang-compiler with (-O3) option. I strongly suggest you use a virtual machine with Linux.

**Comment by mgwoo** [comment]
solved. close
